version: '3.8'
services:
  pg_database:
    build: ./database
    container_name: pg_database
    env_file:
      - pg-env.local.list
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  processing:
    container_name: watcher
    image: localwatcher
    restart: always

volumes:
  db_data:
