version: '3.8'
services:
  pg_database:
    restart: always
    container_name: pg_database
    image: yoyrandao/sw-database:latest
    env_file:
      - pg-env.prod.list
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  processing:
    restart: always
    container_name: sw-service
    image: yoyrandao/sw-service:latest
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  prometheus:
    image: prom/prometheus
    container_name: sw-prom
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  pg_exporter:
    image: bitnami/postgres-exporter
    container_name: sw-pg-exporter
    ports:
      - 9092:9092
    env_file:
      - pg-exporter.prod.list

  grafana:
    image: grafana/grafana
    container_name: sw-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki
    container_name: sw-loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  db_data:
  grafana_data:
