version: '3.8'
services:
  pg_database:
    image: yoyrandao/sw-database:latest
    container_name: pg_database
    env_file:
      - pg-env.prod.list
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  processing:
    image: yoyrandao/sw-service:latest
    container_name: sw-service
    restart: always

volumes:
  db_data:
