name: validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SOLUTION_DIRECTORY: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: setting up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: building solution
        run: dotnet build ${{ env.SOLUTION_DIRECTORY }}
