name: release

on: workflow_dispatch

jobs:
  build_database:
    runs-on: ubuntu-latest

    steps:
      - name: create short sha
        id: short_sha
        uses: benjlevesque/short-sha@v1.2
        with:
          length: 12

      - name: checkout project
        uses: actions/checkout@v2

      - name: logging to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DHUB_USERNAME }}
          password: ${{ secrets.DHUB_ACCESS_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push database
        uses: docker/build-push-action@v2
        env:
          TAG_REF: ${{ steps.short_sha.outputs.sha }}
        with:
          push: true
          file: ./deploy/database/Dockerfile
          context: ./deploy/database/
          tags: |
            ${{ secrets.DHUB_USERNAME }}/sw-database:latest
            ${{ secrets.DHUB_USERNAME }}/sw-database:${{ env.TAG_REF }}

  build_service:
    runs-on: ubuntu-latest

    steps:
      - name: create short sha
        id: short_sha
        uses: benjlevesque/short-sha@v1.2
        with:
          length: 12

      - name: checkout project
        uses: actions/checkout@v2

      - name: decrypt production config
        shell: pwsh
        run: |
          ./build/tools/decrypt-secret.ps1 `
            -secretPath ./build/configurations/production.ss `
            -outPath ./src/StandupWatcher/appsettings.Production.yaml `
            -passphrase "${{ secrets.CONFIGURATION_PASSPHRASE }}"

      - name: logging to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DHUB_USERNAME }}
          password: ${{ secrets.DHUB_ACCESS_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push service
        uses: docker/build-push-action@v2
        env:
          TAG_REF: ${{ steps.short_sha.outputs.sha }}
        with:
          push: true
          file: ./src/StandupWatcher/Dockerfile
          context: ./src/StandupWatcher/
          tags: |
            ${{ secrets.DHUB_USERNAME }}/sw-service:latest
            ${{ secrets.DHUB_USERNAME }}/sw-service:${{ env.TAG_REF }}

  deploy_service:
    runs-on: ubuntu-latest

    needs:
      - build_database
      - build_service

    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: decrypt pg environment variables
        shell: pwsh
        run: |
          ./build/tools/decrypt-secret.ps1 `
            -secretPath ./build/configurations/pg-env.ss `
            -outPath ./build/configurations/pg-env.prod.list `
            -passphrase "${{ secrets.CONFIGURATION_PASSPHRASE }}"

      - name: copy pg-env file to target agent
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AGENT_HOST }}
          key: ${{ secrets.AGENT_PRIVATE_KEY }}
          username: ${{ secrets.AGENT_USERNAME }}
          source: ./build/configurations/pg-env.prod.list
          target: /svc/sw/pg-env.prod.list

      - name: copy docker-compose file to target agent
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AGENT_HOST }}
          key: ${{ secrets.AGENT_PRIVATE_KEY }}
          username: ${{ secrets.AGENT_USERNAME }}
          source: ./deploy/docker-compose.production.yaml
          target: /svc/sw/docker-compose.yaml
